name: Generate issue from error and warning in our logs
on:
  schedule:
  # the day of the month we run zyte – https://crontab.guru
  - cron: 0 0 1 * *

jobs:
  errorReport:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.error_report.outputs.matrix }}
    steps:
      id: error_report
      run: |
        ApiErrors.py secrets.APIKEY '282053'
        MATRIX=$(cat matrix.json)
        echo "${MATRIX}"
        echo "::set-output name=matrix::${MATRIX}"

  create_issue:
    needs: [errorReport]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ${{needs.errorReport.outputs.matrix}}
    steps:
      uses: imjohnbo/issue-bot@v3
        with:
          title: ${{ matrix.node.spider}}
          body: ${{ matrix.node. message}}
