name: Generate issue from error and warning in our logs
on: push

jobs:
  errorReport:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.error_report.outputs.matrix }}
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Run error report
        id: error_report
        run: |
              pip install scrapinghub
              OUTPUT=$(python ApiError.py secrets.APIKEY '282053' )
              echo "::set-output name=OUTPUT::$OUTPUT"
  create_issue:
    needs: [errorReport]
    runs-on: ubuntu-latest 
    strategy:
      matrix:
            ${{fromJson(needs.errorReport.outputs.matrix)}}     
    steps:
      - name: issue maker    
        uses: imjohnbo/issue-bot@v3
        with:
          title: ${{ matrix.spider}}
          body: ${{ matrix. message}}
      
