name: Generate issue from error and warning in our logs
on: push

jobs:
  errorReport:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.error_report.outputs.matrix }}
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Run error report
        id: error_report
        run: |
              pip install scrapinghub
              OUTPUT=$(python ApiError.py '282053' )
              echo "::set-output name=matrix::$OUTPUT"
              
  two:
    runs-on: ubuntu-latest
    needs: one
    steps:
    - run: echo '${{ needs.one.outputs.matrix }}'
    
  create_issue:
    needs: [errorReport]
    runs-on: ubuntu-latest 
    steps:
      - name: issue maker    
        uses: imjohnbo/issue-bot@v3
        with:
          title: ${{needs.errorReport.outputs.matrix.spider}}
          body: ${{needs.errorReport.outputs.matrix.message}}
      
