name: Generate issue from error and warning in our logs
on: 
  schedule:
  # the day of the month we run zyte – https://crontab.guru
  - cron: 0 0 1 * *

jobs:
  errorReport:
    runs-on: ubuntu-latest
    outputs:
      matrix1: ${{ steps.error_report.outputs.errors }}
      matrix2: ${{ steps.error_report.outputs.items }}
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Run error report
        id: error_report
        run: |
              pip install scrapinghub
              errors, items=$(python ApiError.py ${{secrets.APIKEY}} '282053')
              echo "::set-output name=errors::$errors"
              echo "::set-output name=items::$items"


  job2:
    runs-on: ubuntu-latest
    needs: errorReport
    strategy:
      matrix:
            ${{fromJson(needs.errorReport.outputs.matrix1)}} 
    steps:
      - name: issue maker 
        uses: imjohnbo/issue-bot@v3
        with:
          title: ERROR ${{ matrix.spider }}
          body: ${{ matrix.message }}
  job3:
    runs-on: ubuntu-latest
    needs: errorReport
    strategy:
      matrix:
            ${{fromJson(needs.errorReport.outputs.matrix2)}} 
    steps:
      - name: issue maker 
        uses: imjohnbo/issue-bot@v3
        with:
          title: ITEM ${{ matrix.spider }}
          body: ${{ matrix.message }}
            
      
